spring:
  datasource:
    url: jdbc:mysql://119.29.107.83:3306/authtest?useUnicode=true&characterEncoding=utf8&autoReconnect=true&autoReconnectForPools=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xsg435268

#配置session会话超时时间，默认为30秒，但是Spring Boot中的会话超时时间至少为60秒
server:
  servlet:
    session:
      timeout: 60s